version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes_app
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./public:/var/www/html/public
    depends_on:
      - db
    networks:
      - notes_network

  db:
    image: mysql:5.7
    container_name: notes_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notes_root_password
      MYSQL_DATABASE: notes_db
      MYSQL_USER: notes_user
      MYSQL_PASSWORD: notes_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - notes_db_data:/var/lib/mysql
    networks:
      - notes_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: notes_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: notes_root_password
      PMA_USER: notes_user
      PMA_PASSWORD: notes_password
      UPLOAD_LIMIT: 300M
      MEMORY_LIMIT: 256M
    depends_on:
      - db
    networks:
      - notes_network

networks:
  notes_network:
    driver: bridge

volumes:
  notes_db_data: